/**
 * One-time migration: local SQLite (scripts/news-aggregator/output/events.db)
 * → D1 (toolnews-news) via a generated .sql file.
 *
 * Usage:
 *   cd news-worker
 *   npx tsx migrations/seed-from-local.ts      # generates 0002_seed.sql
 *   npx wrangler d1 execute toolnews-news --remote --file=migrations/0002_seed.sql
 */

import Database from 'better-sqlite3';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const LOCAL_DB = join(REPO_ROOT, 'scripts/news-aggregator/output/events.db');
const OUT = join(__dirname, '0002_seed.sql');

const db = new Database(LOCAL_DB, { readonly: true });

function sqlString(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'bigint') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/'/g, "''")}'`;
}

function batchInsert(
  table: string,
  columns: string[],
  rows: Record<string, unknown>[],
  batchSize = 100,
): string[] {
  const statements: string[] = [];
  for (let i = 0; i < rows.length; i += batchSize) {
    const slice = rows.slice(i, i + batchSize);
    const valuesTuples = slice
      .map((r) => `(${columns.map((c) => sqlString(r[c])).join(', ')})`)
      .join(',\n    ');
    statements.push(
      `INSERT OR IGNORE INTO ${table} (${columns.join(', ')}) VALUES\n    ${valuesTuples};`,
    );
  }
  return statements;
}

// ── Handles ─────────────────────────────────────────────────────────────
const handles = db
  .prepare(
    `SELECT handle, user_id, name, category, tier, description, source,
            active, added_at, last_polled_at, last_tweet_id
       FROM handles`,
  )
  .all() as any[];

const handleColumns = [
  'handle',
  'user_id',
  'name',
  'category',
  'tier',
  'description',
  'source',
  'active',
  'added_at',
  'last_polled_at',
  'last_tweet_id',
];

const handleSql = batchInsert('handles', handleColumns, handles, 30);

// ── Events ──────────────────────────────────────────────────────────────
// Skip raw_json — it's only for local debugging and each row can be 2-5KB,
// blowing past D1's SQLITE_TOOBIG limit on batched INSERTs.
const events = db
  .prepare(
    `SELECT id, source, source_handle, url, created_at, ingested_at, title,
            text, lang, like_count, reply_count, retweet_count, view_count,
            score, score_reason, drafts_json, posted,
            pushed_at, tg_message_id, approved_variant
       FROM events`,
  )
  .all() as any[];

const eventColumns = [
  'id',
  'source',
  'source_handle',
  'url',
  'created_at',
  'ingested_at',
  'title',
  'text',
  'lang',
  'like_count',
  'reply_count',
  'retweet_count',
  'view_count',
  'score',
  'score_reason',
  'drafts_json',
  'posted',
  'pushed_at',
  'tg_message_id',
  'approved_variant',
];

const eventSql = batchInsert('events', eventColumns, events, 10);

// ── Compose file ────────────────────────────────────────────────────────
const header = `-- Auto-generated by migrations/seed-from-local.ts
-- ${new Date().toISOString()}
-- Handles: ${handles.length}, Events: ${events.length}
`;

const body = [...handleSql, ...eventSql].join('\n\n');

writeFileSync(OUT, header + '\n' + body + '\n');

const bytes = (header.length + body.length + 2).toLocaleString();

console.log(`Wrote ${OUT}`);
console.log(`  Handles: ${handles.length}`);
console.log(`  Events:  ${events.length}`);
console.log(`  Size:    ${bytes} bytes`);
console.log('');
console.log('Apply to D1 with:');
console.log(`  npx wrangler d1 execute toolnews-news --remote --file=migrations/0002_seed.sql`);
